### ISSUE TITLE
[1.20.1] Enchanting Infuser Incompatibility

### ISSUE THREAD

**Issue by Starexify** [fzzyhmstrs/ai#136]
When I run this mod alongside Enchanting Infuser, it crashes and says its incompatible but then compatible. Why are the mods incompatible if they don't have anything to do with eachother?

Fabric: Fabric-api-0.91.0+1.20.1
Enchanting Infuser Version: v8.0.1-1.20.1
Amethyst Imbuement Version: 1.20.1-18

Log: https://pastebin.com/gHGcYWXR

**Comment by fzzyhmstrs** [comment]
Amethyst Imbuement adds over 100 enchantments of all different types, so they definitely seems to have something to do with each other.

I think I've seen errors from this mod involving my mod before. Looks like instead of trying to fix the issue, they just put an incompatibility flag. Nothing I can do from my end to resolve that.
