### ISSUE TITLE
Possible error with newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [fzzyhmstrs/ai#7]
https://pastebin.com/cqQ7bitL

**Comment by fzzyhmstrs** [comment]
Thank you for the report. Was the modpack working with the previous version of Amethyst Imbuement, but is now crashing with the newest version? Otherwise, this error seems to be originating with Alloy Forgery. I see you have an issue open with them. I'm going to wait until they respond before taking a look myself.
