### ISSUE TITLE
Weird "Crystal witch" error

### ISSUE THREAD

**Issue by nixord** [fzzyhmstrs/ai#71]
Not sure if its the thing not letting me use the enchanting table (using Zenith mod as well) so Im putting the whole log here:
https://paste.ee/p/QsD4R

**Comment by fzzyhmstrs** [comment]
My guess would be Zenith is causing the problem with the enchanting table, since Zenith is the mod that messes with the enchanting table mechanics. AI doesn't alter the enchanting table in any way; it adds the imbuing table as a separate upgrade table. 

I don't know what the error popping up in the log is; I don't have any textures called "amethyst_imbuement:crystal_witch.png" in the assets. This seems like an error in how they are parsing villager profession ids.

**Comment by nixord** [comment]
Ok! Thank you so much! Will consult with Zenith Dev then!
