### ISSUE TITLE
Check magic missile adding back

### ISSUE THREAD

**Issue by fzzyhmstrs** [fzzyhmstrs/ai#96]
Zarra says it still adds back on upgrade

**Comment by Matreats** [comment]
I'm getting some trouble with magic missile, could this be related?

16.10 20:07:57 [Server] main/WARN Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
16.10 20:07:57 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException: category for enchantment amethyst_imbuement:magic_missile is null
16.10 20:07:57 [Server] INFO at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
16.10 20:07:57 [Server] INFO at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.23.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.23.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.23.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.23.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-1.19.2.jar:0.11.2]
16.10 20:07:57 [Server] INFO Caused by: java.lang.NullPointerException: category for enchantment amethyst_imbuement:magic_missile is null
16.10 20:07:57 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.world.item.enchantment.serialize.entry.DataEntry$Builder.add(DataEntry.java:60) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.world.item.enchantment.serialize.entry.DataEntry$Builder.add(DataEntry.java:56) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.world.item.enchantment.serialize.entry.DataEntry.defaultBuilder(DataEntry.java:26) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.core.CommonAbstractions.defaultEnchantmentDataBuilder(CommonAbstractions.java:24) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
16.10 20:07:57 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.world.item.enchantment.data.AdditionalEnchantmentDataProvider.getEnchantmentDataEntries(AdditionalEnchantmentDataProvider.java:50) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.world.item.enchantment.serialize.EnchantmentHoldersManager.loadAll(EnchantmentHoldersManager.java:42) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at fuzs.universalenchants.UniversalEnchantsFabric.lambda$registerHandlers$0(UniversalEnchantsFabric.java:36) ~[UniversalEnchants-v4.2.15-1.19.2-Fabric.jar:?]
16.10 20:07:57 [Server] INFO at net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-cde405b3e4280340.jar:?]
16.10 20:07:57 [Server] INFO at net.minecraft.class_5350.handler$cpc000$fabric-lifecycle-events-v1$hookRefresh(class_5350.java:2033) ~[server-intermediary.jar:?]
16.10 20:08:00 [Multicraft] Skipped 8 lines due to rate limit (30/s)

**Comment by fzzyhmstrs** [comment]
This is an incompatibility with Universal Enchants. It has come up several times before, they really need to fix on their end. Not related to the above issue.
